/**
* This file is auto-generated by grpc-helper
*/

import { Metadata } from '@grpc/grpc-js';

export namespace helloworld {
  export interface Greeter {
    sayHello(data: HelloRequest, metadata?: Metadata): Promise<HelloReply>;
  }
  export interface HelloRequest {
    name?: string;
  }
  export interface HelloReply {
    message?: string;
  }
}

