/**
* This file is auto-generated by grpc-helper
*/

import { Metadata } from '@grpc/grpc-js';

export namespace hello {
  export interface HelloService {
    bidiHello(data: HelloRequest, metadata?: Metadata): Promise<HelloResponse>;
    lotsOfGreetings(data: HelloRequest, metadata?: Metadata): Promise<HelloResponse>;
  }
  export interface HelloRequest {
    greeting?: string;
  }
  export interface HelloResponse {
    reply?: string;
  }
}

