/**
* This file is auto-generated by grpc-helper
*/

import { Metadata } from '@grpc/grpc-js';

export namespace math {
  export interface DivArgs {
    dividend?: number;
    divisor?: number;
  }
  export interface DivReply {
    quotient?: number;
    remainder?: number;
  }
  export interface FibArgs {
    limit?: number;
  }
  export interface Num {
    num?: number;
  }
  export interface FibReply {
    count?: number;
  }
  export interface Math {
    div(data: DivArgs, metadata?: Metadata): Promise<DivReply>;
    divMany(data: DivArgs, metadata?: Metadata): Promise<DivReply>;
    fib(data: FibArgs, metadata?: Metadata): Promise<Num>;
    sum(data: Num, metadata?: Metadata): Promise<Num>;
  }
}

